<!DOCTYPE html>
<html>
<head>
    <title>Course Certificate</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
            background-color: #f3f3f3;
        }
        .container {
            width: 80%;
            margin: 50px auto;
            padding: 40px;
            border: 1px solid #ccc;
            border-radius: 15px;
            background: #fff;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
            text-align: center;
            position: relative;
        }
        .header {
            margin-bottom: 40px;
            position: relative;
        }
        .header h1 {
            font-size: 36px;
            text-transform: uppercase;
            letter-spacing: 2px;
            color: white;
            margin-bottom: 10px;
            background: #3498db;
            padding: 20px 0;
        }
        .header h2 {
            font-size: 28px;
            color: #555;
            margin-top: 0;
        }
        .logo {
            position: absolute;
            top: 10px;
            left: 10px;
            width: 100px;
        }
        .content {
            margin: 30px 0;
        }
        .content p {
            font-size: 20px;
            margin: 10px 0;
        }
        .content p span {
            font-weight: bold;
            color: #3498db;
        }
        .details {
            margin: 40px 0;
            text-align: left;
            display: inline-block;
            width: 100%;
        }
        .details p {
            font-size: 18px;
            line-height: 1.8;
            color: #555;
        }
        .footer {
            margin-top: 20px;
        }
        .footer p {
            font-size: 16px;
            color: #999;
        }
        .signature div {
            width: 45%;
            text-align: center;
        }
        .signature-line {
            margin-top: 20px;
            width: 60%;
            border-top: 2px solid #333;
            margin-left: auto;
            margin-right: auto;
        }
        .signature p {
            font-size: 18px;
            margin-top: 10px;
            color: #333;
        }
        .background {
            position: absolute;
            top: 50%;
            left: 50%;
            width: 80%;
            height: 80%;
            background: url('path/to/background.png') no-repeat center center;
            background-size: cover;
            opacity: 0.05;
            transform: translate(-50%, -50%);
            z-index: -1;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="background"></div>
        <div class="header">
            {{-- <img src="path/to/logo.png" alt="Logo" class="logo"> --}}
            <h1>Course Certificate</h1>
            <h2>Certificate of Completion</h2>
        </div>
        <div class="content">
            <p>This is to certify that <span>{{ $student->name }}</span> has successfully completed the course <span>{{ $course->title }}</span> under the guidance of <span>{{ $teacher->name }}</span></p>
            <p>on {{ $date }}</p>
        </div>
        <div class="flex justify-between mt-16 px-16">
            <div>
                <p>Instructor</p>
                <p><strong>{{ $teacher->name }}</strong></p>
            </div>
            <div>
                <p>Student</p>
                <p><strong>{{ $student->name }}</strong></p>
            </div>
        </div>
        <div class="signature-line"></div>
        <div class="footer">
            <p style="color:black">{{ $time }}</p>
            <p>Generated by Your E-learning System</p>
        </div>
    </div>
</body>
</html>
